In [1]:
import numpy as np
%timeit np.arange(1,9)**4

2.66 µs ± 40.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
%timeit [j**4 for j in range (1,9)]

894 ns ± 50.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [3]:
li = [1,2,3,4,5]
arr1 = np.array(li)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr2 = np.array([[1,2,3,4],[2,3,4,5]])
print(arr2)

[[1 2 3 4]
 [2 3 4 5]]


In [5]:
print(arr2.ndim)

2


In [6]:
arr3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

In [7]:
print(arr3)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


In [8]:
print(arr3.ndim)

3


In [9]:
arrn = np.array([1,2,3,4],ndmin=5)

In [10]:
print(arrn)
print(arrn.ndim)

[[[[[1 2 3 4]]]]]
5


In [11]:
a1_zeroes = np.zeros((3,3))
print(a1_zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
a1_ones = np.ones((3,3))
print(a1_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
a1_range = np.arange(0,10,2)
print(a1_range)

[0 2 4 6 8]


In [14]:
arr1D = np.array([10,20,30,40,50])
print(f"Single element : {arr1D[0]}")
print(f"Negative indexing : {arr1D[-1]}")

Single element : 10
Negative indexing : 50


In [15]:
arr2D = np.array([[2,3,4,5],[5,6,7,8],[3,5,7,9]])
print(f"Multidimensional access : {arr2D[0,2]}")

Multidimensional access : 4


In [16]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(f"Range of Elements : {arr[1:4]}")

Range of Elements : [[5 6 7 8]]


In [17]:
print(f"Multidimensional Slicing : {arr[:,3]}")

Multidimensional Slicing : [4 8]


In [18]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])


In [19]:
indices = np.array([1,3,5])

In [20]:
print(f"Integer array indexing : {arr[indices]}")

Integer array indexing : [20 40 60]


In [21]:
cond = arr > 30
print(f"Element greater than 30 : {arr[cond]}")


Element greater than 30 : [ 40  50  60  70  80  90 100]


In [22]:
x = np.array([1,2,3,4])
y = np.array([2,4,6,8])
print(f"Addition : {x + y}")
print(f"Subtraction : {y - x}")
print(f"Multiplication : {x * y}")
print(f"Division : {y / x}")


Addition : [ 3  6  9 12]
Subtraction : [1 2 3 4]
Multiplication : [ 2  8 18 32]
Division : [2. 2. 2. 2.]


In [24]:
arr = np.array([1,2,3,-3,-7,-9])
result = np.absolute(arr)
print(result)

[1 2 3 3 7 9]


In [26]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.add(arr1, arr2)
print(result)

[5 7 9]


In [29]:
a = np.array([0,np.pi/6,np.pi/4, np.pi/3, np.pi/2])
print(f"Sine values of array elements : {np.sin(a)}")

Sine values of array elements : [0.         0.5        0.70710678 0.8660254  1.        ]


In [35]:
b = np.array([3,4,5])
print(f"Exponent of array elements : {np.exp(b)}")
print(f"Square root of array elements : {np.sqrt(b)}")

Exponent of array elements : [ 20.08553692  54.59815003 148.4131591 ]
Square root of array elements : [1.73205081 2.         2.23606798]
