In [4]:
import numpy as np
%timeit np.arange(1,9)**4

2.52 µs ± 185 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
%timeit [j**4 for j in range (1,9)]

1.37 µs ± 431 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
li = [1,2,3,4,5]
arr = np.array(li)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
arr2 = np.array([[1,2,3,4],[2,3,4,5]])
print(arr2)

[[1 2 3 4]
 [2 3 4 5]]


In [8]:
print(arr2.ndim)

2


In [9]:
arr3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

In [10]:
print(arr3)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


In [11]:
print(arr3.ndim)

3


In [12]:
arrn = np.array(
    
    
    
    
    
    
    [1,2,3,4],ndmin=5)

In [13]:
print(arrn)
print(arrn.ndim)

[[[[[1 2 3 4]]]]]
5


In [14]:
a1_zeroes = np.zeros((3,3))
print(a1_zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
a1_ones = np.ones((3,3))
print(a1_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
a1_range = np.arange(0,10,2)
print(a1_range)

[0 2 4 6 8]


In [17]:
arr1D = np.array([10,20,30,40,50])
print(f"Single element : {arr1D[0]}")
print(f"Negative indexing : {arr1D[-1]}")

Single element : 10
Negative indexing : 50


In [18]:
arr2D = np.array([[2,3,4,5],[5,6,7,8],[3,5,7,9]])
print(f"Multidimensional access : {arr2D[0,2]}")

Multidimensional access : 4


In [19]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(f"Range of Elements : {arr[1:4]}")





Range of Elements : [[5 6 7 8]]


In [20]:
print(f"Multidimensional Slicing : {arr[:,3]}")

Multidimensional Slicing : [4 8]


In [21]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])


In [22]:
indices = np.array([1,3,5])

In [23]:
print(f"Integer array indexing : {arr[indices]}")

Integer array indexing : [20 40 60]


In [24]:
cond = arr > 30
print(f"Element greater than 30 : {arr[cond]}")


Element greater than 30 : [ 40  50  60  70  80  90 100]


In [25]:
x = np.array([1,2,3,4])
y = np.array([2,4,6,8])
print(f"Addition : {x + y}")
print(f"Subtraction : {y - x}")
print(f"Multiplication : {x * y}")
print(f"Division : {y / x}")


Addition : [ 3  6  9 12]
Subtraction : [1 2 3 4]
Multiplication : [ 2  8 18 32]
Division : [2. 2. 2. 2.]


In [26]:
arr = np.array([1,2,3,-3,-7,-9])
result = np.absolute(arr)
print(result)

[1 2 3 3 7 9]


In [27]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.add(arr1, arr2)
print(result)

[5 7 9]


In [28]:
a = np.array([0,np.pi/6,np.pi/4, np.pi/3, np.pi/2])
print(f"Sine values of array elements : {np.sin(a)}")

Sine values of array elements : [0.         0.5        0.70710678 0.8660254  1.        ]


In [29]:
b = np.array([3,4,5])
print(f"Exponent of array elements : {np.exp(b)}")
print(f"Square root of array elements : {np.sqrt(b)}")

Exponent of array elements : [ 20.08553692  54.59815003 148.4131591 ]
Square root of array elements : [1.73205081 2.         2.23606798]


In [30]:
import numpy as np 
# set alias names for dtypes
dtypes = [('name','S10'),('grad_year',int),('cgpa',float)]

# values to be put in array
values = [('Jack',2009,2.96),('Tom',2004,2.56),('Bob',2007,2.64),('Alex',2008,2.67)]

# creating array
arr = np.array(values, dtype=dtypes)
print("Array sorted by names:", np.sort(arr, order='name'))

print("Array sorted by year:",np.sort(arr,order='grad_year'))

print("Array sorted by year & CGPA:",np.sort(arr,order=['grad_year','cgpa']))

Array sorted by names: [(b'Alex', 2008, 2.67) (b'Bob', 2007, 2.64) (b'Jack', 2009, 2.96)
 (b'Tom', 2004, 2.56)]
Array sorted by year: [(b'Tom', 2004, 2.56) (b'Bob', 2007, 2.64) (b'Alex', 2008, 2.67)
 (b'Jack', 2009, 2.96)]
Array sorted by year & CGPA: [(b'Tom', 2004, 2.56) (b'Bob', 2007, 2.64) (b'Alex', 2008, 2.67)
 (b'Jack', 2009, 2.96)]


In [39]:
arr = np.array([[1,2,3,4,5],[5,6,7,8,9],[12,13,14,15,16]])
print(f"Array with first two rows and alternative columns '0' & '3' is {arr[:2,::3]}")

indices = np.array([[1,1,0,2],[2,2,0,1]])
print(f"Elements at (1,0), (1,2), (0,4), (2,2), (2,1) is \n {arr[indices]}")

Array with first two rows and alternative columns '0' & '3' is [[1 4]
 [5 8]]
Elements at (1,0), (1,2), (0,4), (2,2), (2,1) is 
 [[[ 5  6  7  8  9]
  [ 5  6  7  8  9]
  [ 1  2  3  4  5]
  [12 13 14 15 16]]

 [[12 13 14 15 16]
  [12 13 14 15 16]
  [ 1  2  3  4  5]
  [ 5  6  7  8  9]]]


In [41]:
new_arr = arr[indices]
print(new_arr.ndim)

3


In [47]:
# stacking 
a = np.array([[1,2],[4,5]])
b = np.array([[3,5],[7,8]])
print("Vertical stacking:\n", np.vstack((a, b))) 
print("Horizontal stacking:\n", np.hstack((a, b)))
c = [5,6]
print("\nColumn stacking:\n", np.column_stack((a, c))) 

print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1)) 



Vertical stacking:
 [[1 2]
 [4 5]
 [3 5]
 [7 8]]
Horizontal stacking:
 [[1 2 3 5]
 [4 5 7 8]]

Column stacking:
 [[1 2 5]
 [4 5 6]]

Concatenating to 2nd axis:
 [[1 2 3 5]
 [4 5 7 8]]


In [3]:
import numpy as np
a = np.array([[1,2,3,4,5,3],[3,5,6,7,8,1]])

# horizontal splitting 
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2)) 

# vertical splitting 
print("Splitting along vertical axis into 2 parts:\n", np.vsplit(a, 2)) 



Splitting along horizontal axis into 2 parts:
 [array([[1, 2, 3],
       [3, 5, 6]]), array([[4, 5, 3],
       [7, 8, 1]])]
Splitting along vertical axis into 2 parts:
 [array([[1, 2, 3, 4, 5, 3]]), array([[3, 5, 6, 7, 8, 1]])]


In [4]:
# broadcasting
a = np.array([1.0, 2.0, 3.0])

b = 2.0

print(a * b)

c = [2.0, 3.0, 4.0]

print(a * c)

[2. 4. 6.]
[ 2.  6. 12.]


In [5]:
x  = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,2])

print(x[:,np.newaxis]+y)

[[ 7  8  9 10  3]
 [ 8  9 10 11  4]
 [ 9 10 11 12  5]
 [10 11 12 13  6]
 [11 12 13 14  7]]
