In [1]:
import numpy as np
%timeit np.arange(1,9)**4

2.72 µs ± 272 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
%timeit [j**4 for j in range (1,9)]

864 ns ± 117 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
li = [1,2,3,4,5]
arr1 = np.array(li)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr2 = np.array([[1,2,3,4],[2,3,4,5]])
print(arr2)

[[1 2 3 4]
 [2 3 4 5]]


In [6]:
print(arr2.ndim)

2


In [7]:
arr3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

In [8]:
print(arr3)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


In [9]:
print(arr3.ndim)

3


In [10]:
arrn = np.array([1,2,3,4],ndmin=5)

In [11]:
print(arrn)
print(arrn.ndim)

[[[[[1 2 3 4]]]]]
5


In [13]:
a1_zeroes = np.zeros((3,3))
print(a1_zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
a1_ones = np.ones((3,3))
print(a1_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
a1_range = np.arange(0,10,2)
print(a1_range)

[0 2 4 6 8]
