In [6]:
import numpy as np
%timeit np.arange(1,9)**4

2.27 μs ± 57.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
%timeit [j**4 for j in range (1,9)]

635 ns ± 3.15 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
li = [1,2,3,4,5]
arr1 = np.array(li)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
arr2 = np.array([[1,2,3,4],[2,3,4,5]])
print(arr1)

[1 2 3 4 5]


In [20]:
print(arr2.ndim)

2


In [21]:
arr3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

In [22]:
print(arr3)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


In [23]:
print(arr3.ndim)

3


In [25]:
arrn = np.array([1,2,3,4],ndmin=5)

In [ ]:
pri