In [1]:
import numpy as np 
%timeit np.arange(1,9)**4 

4.47 μs ± 2.53 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
%timeit [j**4 for j in range (1,9)] # list comprehension

875 ns ± 58 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [3]:
li = [1,2,3,4,5]
arr = np.array(li) # converting list to array
print(arr) 
print(type(arr)) 

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr2 = np.array([[1,2,3,4],[2,3,4,5]])
print(arr2)

[[1 2 3 4]
 [2 3 4 5]]


In [5]:
print(arr2.ndim)

2


In [6]:
arr3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

In [7]:
print(arr3)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


In [8]:
print(arr3.ndim)

3


In [9]:
arrn = np.array([1,2,3,4],ndmin=5)

In [10]:
print(arrn)
print(arrn.ndim)

[[[[[1 2 3 4]]]]]
5


In [11]:
a1_zeroes = np.zeros((3,3))
print(a1_zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
a1_ones = np.ones((3,3))
print(a1_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
a1_range = np.arange(0,10,2)
print(a1_range)

[0 2 4 6 8]


In [14]:
arr1D = np.array([10,20,30,40,50])
print(f"Single element : {arr1D[0]}")
print(f"Negative indexing : {arr1D[-1]}")

Single element : 10
Negative indexing : 50


In [15]:
arr2D = np.array([[2,3,4,5],[5,6,7,8],[3,5,7,9]])
print(f"Multidimensional access : {arr2D[0,2]}")

Multidimensional access : 4


In [98]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(f"Range of Elements : {arr[1,1:3]}")

Range of Elements : [6 7]


In [99]:
print(f"Multidimensional Slicing : {arr[:,3]}")

Multidimensional Slicing : [4 8]


In [100]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])


In [101]:
indices = np.array([1,3,5])

In [102]:
print(f"Integer array indexing : {arr[indices]}")

Integer array indexing : [20 40 60]


In [103]:
cond = arr > 30
print(f"Element greater than 30 : {arr[cond]}")


Element greater than 30 : [ 40  50  60  70  80  90 100]


In [22]:
x = np.array([1,2,3,4])
y = np.array([2,4,6,8])
print(f"Addition : {x + y}")
print(f"Subtraction : {y - x}")
print(f"Multiplication : {x * y}")
print(f"Division : {y / x}")


Addition : [ 3  6  9 12]
Subtraction : [1 2 3 4]
Multiplication : [ 2  8 18 32]
Division : [2. 2. 2. 2.]


In [23]:
arr = np.array([1,2,3,-3,-7,-9])
result = np.absolute(arr)
print(result)

[1 2 3 3 7 9]


In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.add(arr1, arr2)
print(result)

[5 7 9]


In [25]:
a = np.array([0,np.pi/6,np.pi/4, np.pi/3, np.pi/2])
print(f"Sine values of array elements : {np.sin(a)}")

Sine values of array elements : [0.         0.5        0.70710678 0.8660254  1.        ]


In [26]:
b = np.array([3,4,5])
print(f"Exponent of array elements : {np.exp(b)}")
print(f"Square root of array elements : {np.sqrt(b)}")

Exponent of array elements : [ 20.08553692  54.59815003 148.4131591 ]
Square root of array elements : [1.73205081 2.         2.23606798]


In [27]:
import numpy as np 
# set alias names for dtypes
dtypes = [('name','S10'),('grad_year',int),('cgpa',float)]

# values to be put in array
values = [('Jack',2009,2.96),('Tom',2004,2.56),('Bob',2007,2.64),('Alex',2008,2.67)]

# creating array
arr = np.array(values, dtype=dtypes)
print("Array sorted by names:", np.sort(arr, order='name'))

print("Array sorted by year:",np.sort(arr,order='grad_year'))

print("Array sorted by year & CGPA:",np.sort(arr,order=['grad_year','cgpa']))

Array sorted by names: [(b'Alex', 2008, 2.67) (b'Bob', 2007, 2.64) (b'Jack', 2009, 2.96)
 (b'Tom', 2004, 2.56)]
Array sorted by year: [(b'Tom', 2004, 2.56) (b'Bob', 2007, 2.64) (b'Alex', 2008, 2.67)
 (b'Jack', 2009, 2.96)]
Array sorted by year & CGPA: [(b'Tom', 2004, 2.56) (b'Bob', 2007, 2.64) (b'Alex', 2008, 2.67)
 (b'Jack', 2009, 2.96)]


In [104]:
arr = np.array([[1,2,3,4,5],[5,6,7,8,9],[12,13,14,15,16]])
print(f"Array with first two rows and alternative columns '0' & '3' is {arr[:2,::4]}")

indices = np.array([[1,1,0,2],[2,2,0,1]])
print(f"Elements at (1,0), (1,2), (0,4), (2,2), (2,1) is \n {arr[indices]}")

Array with first two rows and alternative columns '0' & '3' is [[1 5]
 [5 9]]
Elements at (1,0), (1,2), (0,4), (2,2), (2,1) is 
 [[[ 5  6  7  8  9]
  [ 5  6  7  8  9]
  [ 1  2  3  4  5]
  [12 13 14 15 16]]

 [[12 13 14 15 16]
  [12 13 14 15 16]
  [ 1  2  3  4  5]
  [ 5  6  7  8  9]]]


In [29]:
new_arr = arr[indices]
print(new_arr.ndim)

3


In [30]:
# stacking 
a = np.array([[1,2],[4,5]])
b = np.array([[3,5],[7,8]])
print("Vertical stacking:\n", np.vstack((a, b))) 
print("Horizontal stacking:\n", np.hstack((a, b)))
c = [5,6]
print("\nColumn stacking:\n", np.column_stack((a, c))) 

print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1)) 



Vertical stacking:
 [[1 2]
 [4 5]
 [3 5]
 [7 8]]
Horizontal stacking:
 [[1 2 3 5]
 [4 5 7 8]]

Column stacking:
 [[1 2 5]
 [4 5 6]]

Concatenating to 2nd axis:
 [[1 2 3 5]
 [4 5 7 8]]


In [31]:
import numpy as np
a = np.array([[1,2,3,4,5,3],[3,5,6,7,8,1]])

# horizontal splitting 
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2)) 

# vertical splitting 
print("Splitting along vertical axis into 2 parts:\n", np.vsplit(a, 2)) 



Splitting along horizontal axis into 2 parts:
 [array([[1, 2, 3],
       [3, 5, 6]]), array([[4, 5, 3],
       [7, 8, 1]])]
Splitting along vertical axis into 2 parts:
 [array([[1, 2, 3, 4, 5, 3]]), array([[3, 5, 6, 7, 8, 1]])]


In [32]:
# broadcasting
a = np.array([1.0, 2.0, 3.0])

b = 2.0

print(a * b)

c = [2.0, 3.0, 4.0]

print(a * c)

[2. 4. 6.]
[ 2.  6. 12.]


In [33]:
x  = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,2])

print(x[:,np.newaxis]+y)

[[ 7  8  9 10  3]
 [ 8  9 10 11  4]
 [ 9 10 11 12  5]
 [10 11 12 13  6]
 [11 12 13 14  7]]


In [34]:
import numpy as np 

# creating a date 
today = np.datetime64('2025-02-24') 
print("Date is:", today) 
print("Year is:", np.datetime64(today, 'Y')) 

# creating array of dates in a month 
dates = np.arange('2025-02', '2025-03', dtype='datetime64[D]') 
print("\nDates of February, 2025:\n", dates) 
print("Today is February:", today in dates) 

# arithmetic operation on dates 
dur = np.datetime64('2025-05-22') - np.datetime64('2024-05-22') 
print("\nNo. of days:", dur) 
print("No. of weeks:", np.timedelta64(dur, 'W')) 

# sorting dates 
a = np.array(['2017-02-12', '2016-10-13', '2019-05-22'], dtype='datetime64') 
print("\nDates in sorted order:", np.sort(a))


Date is: 2025-02-24
Year is: 2025

Dates of February, 2025:
 ['2025-02-01' '2025-02-02' '2025-02-03' '2025-02-04' '2025-02-05'
 '2025-02-06' '2025-02-07' '2025-02-08' '2025-02-09' '2025-02-10'
 '2025-02-11' '2025-02-12' '2025-02-13' '2025-02-14' '2025-02-15'
 '2025-02-16' '2025-02-17' '2025-02-18' '2025-02-19' '2025-02-20'
 '2025-02-21' '2025-02-22' '2025-02-23' '2025-02-24' '2025-02-25'
 '2025-02-26' '2025-02-27' '2025-02-28']
Today is February: True

No. of days: 365 days
No. of weeks: 52 weeks

Dates in sorted order: ['2016-10-13' '2017-02-12' '2019-05-22']


In [35]:
import numpy as np

In [36]:
arr = np.array([1,2,3,4,5])
print(arr[[True, False,False, False,True]]) # boolean indexing 

[1 5]


In [37]:
arr >= 3 # comparison operator

array([False, False,  True,  True,  True])

In [38]:
arr.mean() # mean of array 

3.0

In [39]:
arr[arr > arr.mean()]

array([4, 5])

In [40]:
arr[~(arr > arr.mean())] # negation

array([1, 2, 3])

In [41]:
arr[(arr==0)|(arr==1)] # bitwise operator

array([1])

In [42]:
arr[(arr>=2)&(arr%2==0)] # bitwise operator

array([2, 4])

In [43]:
a = np.arange(5) # array creation
print(a<=3) # comparison operator

[ True  True  True  True False]


In [44]:
A = np.random.randint(100,size=(3,3)) # random array creation
print(A)

[[87 97  0]
 [61 63 57]
 [13 92 39]]


In [45]:
A[np.array([[True, False, True],[False, True, False],[True, False, True]])] # boolean indexing

array([87,  0, 63, 13, 39])

In [46]:
A > 30 # comparison operator

array([[ True,  True, False],
       [ True,  True,  True],
       [False,  True,  True]])

In [47]:
print(A[A>30]) # boolean indexing

[87 97 61 63 57 92 39]


In [48]:
import numpy as np

In [49]:
X = np.array([[1,2,3],[4,8,6],[7,8,9]])

In [50]:
Y = np.array([[6,5],[4,3],[2,1]])

In [51]:
X.dot(Y) # matrix multiplication

array([[20, 14],
       [68, 50],
       [92, 68]])

In [52]:
X@Y # matrix multiplication

array([[20, 14],
       [68, 50],
       [92, 68]])

In [53]:
Y.T # transpose of matrix

array([[6, 4, 2],
       [5, 3, 1]])

In [54]:
X

array([[1, 2, 3],
       [4, 8, 6],
       [7, 8, 9]])

In [55]:
Y.T @ X

array([[36, 60, 60],
       [24, 42, 42]])

In [56]:
np.linalg.inv(X) # inverse of matrix

array([[-0.66666667, -0.16666667,  0.33333333],
       [-0.16666667,  0.33333333, -0.16666667],
       [ 0.66666667, -0.16666667,  0.        ]])

In [57]:
import sys
sys.getsizeof(3) # size of integer

28

In [58]:
sys.getsizeof(10**100) # size of large integer

72

In [59]:
np.dtype(int).itemsize # size of integer

8

In [60]:
np.dtype(float).itemsize # size of float

8

In [61]:
np.dtype(np.int8).itemsize # size of int8

1

In [62]:
np.random.random(size=2) # random number generation

array([0.02712777, 0.64355773])

In [63]:
np.random.normal(size=2) # random number generation

array([-0.69422272, -0.77698278])

In [64]:
np.random.rand(3,4) # random number generation

array([[0.84137139, 0.3807441 , 0.20970865, 0.48217664],
       [0.64698037, 0.57427896, 0.37719729, 0.61012773],
       [0.60146646, 0.4616093 , 0.84648915, 0.96486592]])

In [65]:
np.arange(10) # array creation

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.arange(5,10) # array creation

array([5, 6, 7, 8, 9])

In [67]:
np.arange(0,10,2) # even number array creation

array([0, 2, 4, 6, 8])

In [68]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [69]:
np.arange(10).reshape(2,5) # array reshaping

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [71]:
np.linspace(0,1,20) # linear space creation

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [72]:
np.linspace(0,1,20,False) # exclude last element

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [105]:
import numpy as np
a = np.array([1,2,3,4])
a.itemsize

8

In [107]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [110]:
b[1,3:]

array([11, 12, 13, 14])

In [111]:
b[:,3]

array([ 4, 11])

In [ ]:
b[0,0:-1:2] # access with step size '2' starting from index '0' excluding last element

array([1, 3, 5])

In [117]:
b[1,5] = 20

In [118]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [14]:
import numpy as np

In [15]:
output = np.zeros((7,7),dtype=float)
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [24]:
ones = np.ones((5,5),dtype=float)
ones[2,2] = 5
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
output[1:-1,1:-1] = ones

print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [38]:
names = np.array(['Jack','Tom','Bob','Alice'])

entry_names = names[~np.char.startswith(names, 'A')] # names not starting with 'A'

print(entry_names)

print(names)

['Jack' 'Tom' 'Bob']
['Jack' 'Tom' 'Bob' 'Alice']
